import { request } from '@/utils/request';
export const datasourceApi = {
    check: (data) => request.post('/datasource/check', data),
    check_by_id: (id) => request.get(`/datasource/check/${id}`),
    relationGet: (id) => request.post(`/table_relation/get/${id}`),
    relationSave: (dsId, data) => request.post(`/table_relation/save/${dsId}`, data),
    add: (data) => request.post('/datasource/add', data),
    importToDb: (data) => request.post('/datasource/importToDb', data),
    list: () => request.get('/datasource/list'),
    update: (data) => request.post('/datasource/update', data),
    delete: (id, name) => request.post(`/datasource/delete/${id}/${name}`),
    getTables: (id) => request.post(`/datasource/getTables/${id}`),
    getTablesByConf: (data) => request.post('/datasource/getTablesByConf', data),
    getFields: (id, table_name) => request.post(`/datasource/getFields/${id}/${table_name}`),
    execSql: (id, sql) => request.post(`/datasource/execSql/${id}`, { sql: sql }),
    chooseTables: (id, data) => request.post(`/datasource/chooseTables/${id}`, data),
    tableList: (id) => request.post(`/datasource/tableList/${id}`),
    fieldList: (id, data = { fieldName: '' }) => request.post(`/datasource/fieldList/${id}`, data),
    edit: (data) => request.post('/datasource/editLocalComment', data),
    previewData: (id, data) => request.post(`/datasource/previewData/${id}`, data),
    saveTable: (data) => request.post('/datasource/editTable', data),
    saveField: (data) => request.post('/datasource/editField', data),
    getDs: (id) => request.post(`/datasource/get/${id}`),
    getSchema: (data) => request.post('/datasource/getSchemaByConf', data),
    syncFields: (id) => request.post(`/datasource/syncFields/${id}`),
    exportDsSchema: (id) => request.get(`/datasource/exportDsSchema/${id}`, {
        responseType: 'blob',
        requestOptions: { customError: true },
    }),
    batchUpdateFieldComments: (data) => request.post('/datasource/batchUpdateFieldComments', data),
};
